version: '3.2'

services:
  web: &base
    image: ada/backend-challenge:andre
    build:
      context: .
      dockerfile: ./cmd/backend-challenge/Dockerfile
    environment:
      - ADA_TOKEN
    env_file:
      - ./deployments/docker-compose/env/base.env
    ports:
      - "${ADA_WEB_HTTP_PORT}:8000"
    depends_on:
      - db
    networks:
      - ada_public
      - ada_internal

  db:
    image: mysql:8.0
    env_file:
      - ./deployments/docker-compose/env/db.env
    networks:
      - ada_internal
    volumes:
      - db_mysql:/var/lib/mysql
      - ./deployments/docker-compose/db/conversations.sql:/docker-entrypoint-initdb.d/conversations.sql
    command: --default-authentication-plugin=mysql_native_password
    restart: always

volumes:
  db_mysql:
  
networks:
  ada_public:
  ada_internal:
